package org.trypticon.irc;

/**
 * The numeric constants which form the more standard part of the IRC protocol.
 */
public interface IrcNumerics {
    // 6.1. Error Replies
    int ERR_NOSUCHNICK = 401; // "<nickname> :No such nick/channel"
    int ERR_NOSUCHSERVER = 402; // "<server name> :No such server"
    int ERR_NOSUCHCHANNEL = 403; // "<channel name> :No such channel"
    int ERR_CANNOTSENDTOCHAN = 404; // "<channel name> :Cannot send to channel"
    int ERR_TOOMANYCHANNELS = 405; // "<channel name> :You have joined too many channels"
    int ERR_WASNOSUCHNICK = 406; // "<nickname> :There was no such nickname"
    int ERR_TOOMANYTARGETS = 407; // "<target> :Duplicate recipients. No message delivered"
    int ERR_NOORIGIN = 409; // ":No origin specified"
    int ERR_NORECIPIENT = 411; // ":No recipient given (<command>)"
    int ERR_NOTEXTTOSEND = 412; // ":No text to send"
    int ERR_NOTOPLEVEL = 413; // "<mask> :No toplevel domain specified"
    int ERR_WILDTOPLEVEL = 414; // "<mask> :Wildcard in toplevel domain"
    int ERR_UNKNOWNCOMMAND = 421; // "<command> :Unknown command"
    int ERR_NOMOTD = 422; // ":MOTD File is missing"
    int ERR_NOADMININFO = 423; // "<server> :No administrative info available"
    int ERR_FILEERROR = 424; // ":File error doing <file op> on <file>"
    int ERR_NONICKNAMEGIVEN = 431; // ":No nickname given"
    int ERR_ERRONEUSNICKNAME = 432; // "<nick> :Erroneus nickname"
    int ERR_NICKNAMEINUSE = 433; // "<nick> :Nickname is already in use"
    int ERR_NICKCOLLISION = 436; // "<nick> :Nickname collision KILL"
    int ERR_USERNOTINCHANNEL = 441; // "<nick> <channel> :They aren't on that channel"
    int ERR_NOTONCHANNEL = 442; // "<channel> :You're not on that channel"
    int ERR_USERONCHANNEL = 443; // "<user> <channel> :is already on channel"
    int ERR_NOLOGIN = 444; // "<user> :User not logged in"
    int ERR_SUMMONDISABLED = 445; // ":SUMMON has been disabled"
    int ERR_USERSDISABLED = 446; // ":USERS has been disabled"
    int ERR_NOTREGISTERED = 451; // ":You have not registered"
    int ERR_NEEDMOREPARAMS = 461; // "<command> :Not enough parameters"
    int ERR_ALREADYREGISTRED = 462; // ":You may not reregister"
    int ERR_NOPERMFORHOST = 463; // ":Your host isn't among the privileged"
    int ERR_PASSWDMISMATCH = 464; // ":Password incorrect"
    int ERR_YOUREBANNEDCREEP = 465; // ":You are banned from this server"
    int ERR_KEYSET = 467; // "<channel> :Channel key already set"
    int ERR_CHANNELISFULL = 471; // "<channel> :Cannot join channel (+l)"
    int ERR_UNKNOWNMODE = 472; // "<char> :is unknown mode char to me"
    int ERR_INVITEONLYCHAN = 473; // "<channel> :Cannot join channel (+i)"
    int ERR_BANNEDFROMCHAN = 474; // "<channel> :Cannot join channel (+b)"
    int ERR_BADCHANNELKEY = 475; // "<channel> :Cannot join channel (+k)"
    int ERR_NOPRIVILEGES = 481; // ":Permission Denied- You're not an IRC operator"
    int ERR_CHANOPRIVSNEEDED = 482; // "<channel> :You're not channel operator"
    int ERR_CANTKILLSERVER = 483; // ":You cant kill a server!"
    int ERR_NOOPERHOST = 491; // ":No O-lines for your host"
    int ERR_UMODEUNKNOWNFLAG = 501; // ":Unknown MODE flag"
    int ERR_USERSDONTMATCH = 502; // ":Cant change mode for other users"
    // 6.2. Command responses
    int RPL_NONE = 300; // Dummy reply number. Not used.
    int RPL_AWAY = 301; // "<nick> :<away message>"
    int RPL_USERHOST = 302; // ":[<reply>{<space><reply>}]"   (<reply> ::= <nick>['*'] '=' <'+'|'-'><hostname>)
    int RPL_ISON = 303; // ":[<nick> {<space><nick>}]"
    int RPL_UNAWAY = 305; // ":You are no longer marked as being away"
    int RPL_NOWAWAY = 306; // ":You have been marked as being away"
    int RPL_WHOISUSER = 311; // "<nick> <user> <host> * :<real name>"
    int RPL_WHOISSERVER = 312; // "<nick> <server> :<server info>"
    int RPL_WHOISOPERATOR = 313; // "<nick> :is an IRC operator"
    int RPL_WHOWASUSER = 314; // "<nick> <user> <host> * :<real name>"
    int RPL_ENDOFWHO = 315; // "<name> :End of /WHO list"
    int RPL_WHOISIDLE = 317; // "<nick> <integer> :seconds idle"
    int RPL_ENDOFWHOIS = 318; // "<nick> :End of /WHOIS list"
    int RPL_WHOISCHANNELS = 319; // "<nick> :{[@|+]<channel><space>}"
    int RPL_LISTSTART = 321; // "Channel :Users  Name"
    int RPL_LIST = 322; // "<channel> <# visible> :<topic>"
    int RPL_LISTEND = 323; // ":End of /LIST"
    int RPL_CHANNELMODEIS = 324; // "<channel> <mode> <mode params>"
    int RPL_NOTOPIC = 331; // "<channel> :No topic is set"
    int RPL_TOPIC = 332; // "<channel> :<topic>"
    int RPL_INVITING = 341; // "<channel> <nick>"
    int RPL_SUMMONING = 342; // "<user> :Summoning user to IRC"
    int RPL_VERSION = 351; // "<version>.<debuglevel> <server> :<comments>"
    int RPL_WHOREPLY = 352; // "<channel> <user> <host> <server> <nick> <H|G>[*][@|+] :<hopcount> <real name>"
    int RPL_NAMREPLY = 353; // "<channel> :[[@|+]<nick> [[@|+]<nick> [...]]]"
    int RPL_LINKS = 364; // "<mask> <server> :<hopcount> <server info>"
    int RPL_ENDOFLINKS = 365; // "<mask> :End of /LINKS list"
    int RPL_ENDOFNAMES = 366; // "<channel> :End of /NAMES list"
    int RPL_BANLIST = 367; // "<channel> <banid>"
    int RPL_ENDOFBANLIST = 368; // "<channel> :End of channel ban list"
    int RPL_ENDOFWHOWAS = 369; // "<nick> :End of WHOWAS"
    int RPL_INFO = 371; // ":<string>"
    int RPL_MOTD = 372; // ":- <text>"
    int RPL_ENDOFINFO = 374; // ":End of /INFO list"
    int RPL_MOTDSTART = 375; // ":- <server> Message of the day - "
    int RPL_ENDOFMOTD = 376; // ":End of /MOTD command"
    int RPL_YOUREOPER = 381; // ":You are now an IRC operator"
    int RPL_REHASHING = 382; // "<config file> :Rehashing"
    int RPL_TIME = 391; // "<server> :<string showing server's local time>"
    int RPL_USERSSTART = 392; // ":UserID   Terminal  Host"
    int RPL_USERS = 393; // ":%-8s %-9s %-8s"
    int RPL_ENDOFUSERS = 394; // ":End of users"
    int RPL_NOUSERS = 395; // ":Nobody logged in"
    int RPL_TRACELINK = 200; // "Link <version & debug level> <destination> <next server>"
    int RPL_TRACECONNECTING = 201; // "Try. <class> <server>"
    int RPL_TRACEHANDSHAKE = 202; // "H.S. <class> <server>"
    int RPL_TRACEUNKNOWN = 203; // "???? <class> [<client IP address in dot form>]"
    int RPL_TRACEOPERATOR = 204; // "Oper <class> <nick>"
    int RPL_TRACEUSER = 205; // "User <class> <nick>"
    int RPL_TRACESERVER = 206; // "Serv <class> <int>S <int>C <server> <nick!user|*!*>@<host|server>"
    int RPL_TRACENEWTYPE = 208; // "<newtype> 0 <client name>"
    int RPL_STATSLINKINFO = 211; // "<linkname> <sendq> <sent messages> <sent bytes> <received messages> <received bytes> <time open>"
    int RPL_STATSCOMMANDS = 212; // "<command> <count>"
    int RPL_STATSCLINE = 213; // "C <host> * <name> <port> <class>"
    int RPL_STATSNLINE = 214; // "N <host> * <name> <port> <class>"
    int RPL_STATSILINE = 215; // "I <host> * <host> <port> <class>"
    int RPL_STATSKLINE = 216; // "K <host> * <username> <port> <class>"
    int RPL_STATSYLINE = 218; // "Y <class> <ping frequency> <connect frequency> <max sendq>"
    int RPL_ENDOFSTATS = 219; // "<stats letter> :End of /STATS report"
    int RPL_UMODEIS = 221; // "<user mode string>"
    int RPL_STATSLLINE = 241; // "L <hostmask> * <servername> <maxdepth>"
    int RPL_STATSUPTIME = 242; // ":Server Up %d days %d:%02d:%02d"
    int RPL_STATSOLINE = 243; // "O <hostmask> * <name>"
    int RPL_STATSHLINE = 244; // "H <hostmask> * <servername>"
    int RPL_LUSERCLIENT = 251; // ":There are <integer> users and <integer> invisible on <integer> servers"
    int RPL_LUSEROP = 252; // "<integer> :operator(s) online"
    int RPL_LUSERUNKNOWN = 253; // "<integer> :unknown connection(s)"
    int RPL_LUSERCHANNELS = 254; // "<integer> :channels formed"
    int RPL_LUSERME = 255; // ":I have <integer> clients and <integer> servers"
    int RPL_ADMINME = 256; // "<server> :Administrative info"
    int RPL_ADMINLOC1 = 257; // ":<admin info>"
    int RPL_ADMINLOC2 = 258; // ":<admin info>"
    int RPL_ADMINEMAIL = 259; // ":<admin info>"
    int RPL_TRACELOG = 261; // "File <logfile> <debug level>"
    // 6.3. Reserved numerics
    int RPL_TRACECLASS = 209;
    int RPL_STATSQLINE = 217;
    int RPL_SERVICEINFO = 231;
    int RPL_ENDOFSERVICES = 232;
    int RPL_SERVICE = 233;
    int RPL_SERVLIST = 234;
    int RPL_SERVLISTEND = 235;
    int RPL_WHOISCHANOP = 316;
    int RPL_KILLDONE = 361;
    int RPL_CLOSING = 362;
    int RPL_CLOSEEND = 363;
    int RPL_INFOSTART = 373;
    int RPL_MYPORTIS = 384;
    int ERR_YOUWILLBEBANNED = 466;
    int ERR_BADCHANMASK = 476;
    int ERR_NOSERVICEHOST = 492;
}
